services:
  db:
    image: postgres:15
    container_name: gp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gp_pass}
      POSTGRES_DB: ${POSTGRES_DB:-gp_db}
    ports:
      - "5432:5432"
    volumes:
      - gp_data:/var/lib/postgresql/data
    networks:
      - gp-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: page_admin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=1234'
      - 'PGADMIN_CONFIG_SERVER_MOD=False'
    volumes:
      - gp_data:/var/lib/postgresql/data
    networks:
      - gp-net
    ports:
      - '5050:80'
    restart: unless-stopped

  backend:
    build: ./back/
    container_name: gp_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://gp_user:gp_pass@db:5432/gp_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gp_user -d gp_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./back/:/app
    networks:
      - gp-net
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  dashboard:
    build:
      context: ./dashboard/
    container_name: gp_dashboard
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./dashboard:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - backend
    networks:
      - gp-net
    command: >
      sh -c "
        if [ ! -d vendor ]; then
          composer install;
        fi &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  gp_data:
networks:
  gp-net:
    driver: bridge
