version: '3.9'

services:
  db:
    image: postgres:15
    container_name: gp_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gp_pass}
      POSTGRES_DB: ${POSTGRES_DB:-gp_db}
    ports:
      - "5432:5432"
    volumes:
      - gp_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gp_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: >
      bash -c "alembic upgrade head &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  gp_data:
